const fakeData = [
  {
    system: "Sabre",
    segment: "2",
    uId: "f84fd1e6abcb20b16f25fcc736443e71ef0b6e4e",
    triptype: "Outbound",
    career: "UK",
    careerName: "Vistara",
    lastTicketTime: "2023-06-30 23:59",
    BasePrice: "23850",
    Taxes: "8390",
    netfare: "30667",
    agentprice: "30667",
    customerPrice: 32240,
    pricebreakdown: [
      {
        BaseFare: "23850",
        Tax: "8390",
        PaxCount: "1",
        PaxType: "ADT",
        Discount: "0",
        OtherCharges: "0",
        ServiceFee: "0",
      },
    ],
    departure: "DAC",
    departureTime: "11:45",
    departureDate: "Wed 20 Sep 2023",
    arrival: "DXB",
    arrivalTime: "18:15",
    arrivalDate: "Wed 20 Sep 2023",
    flightduration: "8H 30Min",
    bags: "30",
    seat: "9",
    class: "Economy",
    refundable: "Refundable",
    segments: [
      {
        marketingcareer: "UK",
        marketingcareerName: "Vistara",
        marketingflight: "184",
        operatingcareer: "UK",
        operatingflight: "184",
        operatingCarrierName: "Vistara",
        departure: "DAC",
        departureAirport: "Hazrat Shahjalal Intl Airport ",
        departureLocation: "Dhaka , BD",
        departureTime: "2023-09-20T11:45:00",
        arrival: "BOM",
        arrivalTime: "2023-09-20T14:05:00",
        arrivalAirport: "Chhatrapati Shivaji",
        arrivalLocation: "Mumbai , IN",
        flightduration: "2H 50Min",
        bookingcode: "Q",
        seat: "9",
      },
      {
        marketingcareer: "UK",
        marketingcareerName: "Vistara",
        marketingflight: "201",
        operatingcareer: "UK",
        operatingflight: "201",
        operatingCarrierName: "Vistara",
        departure: "BOM",
        departureAirport: "Chhatrapati Shivaji",
        departureLocation: "Mumbai , IN",
        departureTime: "2023-09-20T16:25:00",
        arrival: "DXB",
        arrivalTime: "2023-09-20T18:15:00",
        arrivalAirport: "Dubai Intl Airport",
        arrivalLocation: "Dubai , AE",
        flightduration: "3H 20Min",
        bookingcode: "Q",
        seat: "9",
      },
    ],
    transit: {
      transit1: "2H 20Min",
    },
  },
];

export default fakeData;
