version: '3'
services:
  main_flyfarladies:
    build: .
    image: flyfarladies-react-main-main_flyfarladies:latest
    ports:
      - "3000:3000"
    networks:
      - main-net
networks:
  main-net:
    driver: bridge
