const data = [
  {
    id: 1,
    status: 'deposit',
    creatdData: 'Airticket',
    amount: '5212124',
    receipt: 'View Receipt',
    totalAmount: 565145,
    type: 'Bank Transfer',
    rejectedReson: 'NA',
  },
  {
    id: 2,
    status: 'credit',
    creatdData: 'Helicapter',
    amount: '33330',
    receipt: '',
    totalAmount: 565245,
    type: 'Bank Transfer',
    rejectedReson: 'NA',
  },
  {
    id: 3,
    status: 'credit',
    creatdData: 'Airticket',
    amount: '5212124',
    receipt: 'View Receipt',
    totalAmount: 565345,
    type: 'Bank Transfer',
    rejectedReson: 'NA',
  },
  {
    id: 4,
    status: 'deposit',
    creatdData: 'Airticket',
    amount: '5212124',
    receipt: 'View Receipt',
    totalAmount: 545245,
    type: 'Bank Transfer',
    rejectedReson: 'NA',
  },
  {
    id: 5,
    status: 'debit',
    creatdData: 'Airticket',
    amount: '5212124',
    receipt: 'View Receipt',
    totalAmount: 5245,
    type: 'Bank Transfer',
    rejectedReson: 'NA',
  },
  {
    id: 6,
    status: 'debit',
    creatdData: 'train',
    amount: '5212124',
    receipt: 'View Receipt',
    totalAmount: 1111,
    type: 'Nagad Transfer',
    rejectedReson: 'NA',
  },
];

export default data;
